import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavbarUser from './components/commons/NavbarUser';
import UserSidebar from './components/commons/UserSidebar';
import FooterBar from './components/commons/FooterBar';
import { CartProvider } from './context/cartcontext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next-Step',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: '/running.png', type: 'image/png' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="flex min-h-screen flex-col antialiased">
        <CartProvider>
          <NavbarUser />
          <UserSidebar />
          <main className="flex-grow">{children}</main>
          <FooterBar />
        </CartProvider>
      </body>
    </html>
  );
}